{ATENÇÃO: Esta rotina ainda está em desenvolvimento.
          O código gerado pode apresentar incorreções sintáticas. }
program Leitor de usuario;
uses Crt;
// { Disciplina   : [Linguagem e Lógica de Programação]}
// { Professor   : Antonio Carlos Nicolodi}
// { Descrição   : Aqui você descreve o que o programa faz! (função)}
// { Autor(a)    : Rafael}
// { Data atual  : 16/10/2020}
Var
nome: string;


begin
   write('Ola, digite seu nome: ');
   readln (nome);
   writeln('Bem vindo ', nome);


end.