{ATENÇÃO: Esta rotina ainda está em desenvolvimento.
          O código gerado pode apresentar incorreções sintáticas. }
program Ola mundo;
uses Crt;
// { Disciplina   : [Linguagem e Lógica de Programação]}
// { Professor   : Antonio Carlos Nicolodi}
// { Descrição   : Aqui você descreve o que o programa faz! (função)}
// { Autor(a)    : Nome do(a) aluno(a)}
// { Data atual  : 16/10/2020}
Var
// { Seção de Declarações das variáveis}


begin
   // { Seção de Comandos, procedimento, funções, operadores, etc...}
   write('ola mundo');

end.